### ISSUE TITLE
sequence/mapM on Monad

### ISSUE THREAD

**Issue by tonymorris** [palladin/Higher#4]
Only `Applicative` is necessary for these operations. Haskell uses `Monad` for historical reasons.

**Comment by gmpl** [comment]
@tonymorris that's true. In [FsControl](https://github.com/gmpl/FsControl) I defined [sequenceA](https://github.com/gmpl/FsControl/blob/b52542770104bcab9fcf79778fb7b4c815d9eed9/FsControl.Core/Operators.fs#L155) based on Applicatives and removed mapM since it's applicative version already exists, it's [traverse](https://github.com/gmpl/FsControl/blob/b52542770104bcab9fcf79778fb7b4c815d9eed9/FsControl.Core/Operators.fs#L152).
I think in Haskell they were based on monads because Applicative wasn't there at that time.

**Comment by palladin** [comment]
@tonymorris @gmpl Yes you are correct that sequence/mapM can be subsumed by
sequenceA :: (Traversable t, Applicative f) => t (f a) -> f (t a) and 
traverse :: (Traversable t, Applicative f) => (a -> f b) -> t a -> f (t b) 
but my intention back then was to implement the classic sequence/mapM with the monad {  } builder.
